### PR TITLE
Add indexeddb demo

### PR DESCRIPTION
**Pull request by wbamberg**
To fix https://github.com/mdn/content/issues/10941, this PR transfers the demo currently at https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API/Using_IndexedDB#full_indexeddb_example, because I don't think long-form demos work very well as huge code blocks in the page.

The code needs some attention, but I thought it would be better to transfer it first, then improve it once it is here.

### CODE REVIEW

**Review by Elchi3 — APPROVED** [review]
Good idea to move this large chunk of code here but haven't reviewed it itself. As you say, improvements/fixes can come after the initial import.

**Review by Elchi3 — CHANGES_REQUESTED** [review]
Oh, approved too fast! There is a commit to the resize observer example which shouldn't be part of this PR

**Comment by wbamberg** [comment]
Oops, thank you for catching that @Elchi3 . Should be fixed now?

**Comment by wbamberg** [comment]
> Good idea to move this large chunk of code here but haven't reviewed it itself. As you say, improvements/fixes can come after the initial import.

I have checked it works, but it is very much in need of improvement. But I thought it would be much easier to review by moving it as-is, then applying changes in a separate PR.

**Review by Elchi3 — APPROVED** [review]
Yup, all good now

**Pull request merged**
