### PR TITLE
Added Sepia effect

### PR DESCRIPTION
**Pull request by tusharv**
Added Sepia Effect based on following logic

```
 sepiaRed = .393 * originalRed + .769 * originalGreen + .189 * originalBlue
 sepiaGreen = .349 * originalRed + .686 * originalGreen + .168 * originalBlue
 sepiaBlue = .272 * originalRed + .534 * originalGreen + .131 * originalBlue
```

Rerefence - https://cs50.harvard.edu/x/2020/psets/4/filter/less/#sepia

### CODE REVIEW

**Review by chrisdavidmills — APPROVED** [review]
Thanks @tusharv , this works great.

**Comment by chrisdavidmills** [comment]
Do you think you could also update the source of the related tutorial: https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API/Tutorial/Pixel_manipulation_with_canvas#Grayscaling_and_inverting_colors

?

**Comment by tusharv** [comment]
Sure @chrisdavidmills 
I'll do all related changes too.

**Comment by chrisdavidmills** [comment]
Thanks @tusharv - much appreciated!

**Pull request merged**
