### PR TITLE
Add chroma keying

### PR DESCRIPTION
**Pull request by wbamberg**
This migrates the live example from developer.mozilla.org/samples to GitHub, in an attempt to fix https://bugzilla.mozilla.org/show_bug.cgi?id=1501297, specifically as Julien suggests in comment 3: https://bugzilla.mozilla.org/show_bug.cgi?id=1501297#c3..

It adds "canvas/chroma-keying", that contains an HTML file and a JS file corresponding to the files discussed in https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API/Manipulating_video_using_canvas, as well as the media files used in the example.

I've tested this at https://wbamberg.github.io/dom-examples/canvas/chroma-keying/ and it seems to work fine.

### CODE REVIEW

**Comment by wbamberg** [comment]
I've updated the PR, and also the version at https://wbamberg.github.io/dom-examples/canvas/chroma-keying/, so you can see it working. And now it works in Safari too :).

**Comment by chrisdavidmills** [comment]
Great stuff. But now it no longer seems to work in Fx ;-)

**Comment by wbamberg** [comment]
It works for me in Firefox, at https://wbamberg.github.io/dom-examples/canvas/chroma-keying/:

chroma-keying

Do you see any errors in the console?

**Comment by wbamberg** [comment]
Thanks @chrisdavidmills ! I'm not a collaborator on this repo, so I can't merge it, so could you do that too? Or make me a collaborator of course :).

**Comment by chrisdavidmills** [comment]
How about both? I'll send you an invite in a moment.

**Pull request merged**
