### PR TITLE
Make EditContext demo match the MDN tutorial (remove useless `setInterval`, debug mode, reorganize in files, clean up code)

### PR DESCRIPTION
**Pull request by captainbrosset**
This is to make the EditContext API demo match the tutorial being written in https://github.com/mdn/content/pull/32027.

- Removal of `setInterval`, which makes it hard to debug the demo with DevTools.
- Removal of the debug mode helped me during development, but is making the demo code harder to follow now.
- Split the demo into multiple files.
- Removed some code ambiguity.
- General refactoring and cleanup.

### CODE REVIEW

**Comment by bsmth** [comment]
Taking a look now 👀

**Comment by captainbrosset** [comment]
Sorry @bsmth , I may need to do a couple more changes. Please hold off.

**Review by bsmth — COMMENTED** [review]
Looks good to me, thanks! I took a look through the diffs and tested using:

```bash
cd edit-context/html-editor
http-server -c-1
```

Also compared with the deployed example and looks good.

* Not working on FX ([as expected](https://developer.mozilla.org/en-US/docs/Web/API/EditContext#browser_compatibility))
* Works as expected in Chrome Version 122.0.6261.129

**Comment by captainbrosset** [comment]
> BTW, the guide is 404ing: https://github.com/mdn/dom-examples/tree/main/edit-context#demos

I'm working on it now in this PR https://github.com/mdn/content/pull/32027
Hope it's ok to leave the link in for now, as I expect to be able to merge that PR in the not too distant future.

**Comment by bsmth** [comment]
> Sorry @bsmth , I may need to do a couple more changes. Please hold off.

Oops, I was too fast. You can ping me again when you're ready

**Comment by captainbrosset** [comment]
> Oops, I was too fast. You can ping me again when you're ready

No it's my fault! I thought it would be just the one initial change, but then ended up doing more changes. I should have switch it to draft earlier. Thanks for the time spent on this already! I'll ping you again as soon as I'm done.

**Comment by captainbrosset** [comment]
@bsmth I'm done with my changes. Over to you for review, whenever you have some time.

**Comment by bsmth** [comment]
Having another look now 👀

**Review by bsmth — APPROVED** [review]
Thanks a lot, mostly just reviewed https://github.com/mdn/dom-examples/pull/266/commits/c0818e35f5ad010a9c3e3a9f6d72e2c389d4b010 since the last approval. Tested in Chrome again and looking good!

Thank you! 👍🏻

**Comment by captainbrosset** [comment]
Awesome! Feel free to merge whenever.

**Pull request merged**
