### PR TITLE
Avoid Security Error

### PR DESCRIPTION
**Pull request by severo**
See https://developer.mozilla.org/en-US/docs/Web/HTML/CORS_enabled_image.

### CODE REVIEW

**Comment by wbamberg** [comment]
Thanks for the PR!

Can you please elaborate what the security error is here? The page this example is used in (https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API/Manipulating_video_using_canvas) works fine for me in Firefox and Chrome, with no relevant console errors.

**Comment by severo** [comment]
Sure, sorry. The error only appears when the video src is located on another domain than the code.
The error is:

> SecurityError: The operation is insecure.

And it comes from calling [`getImageData`](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/getImageData), as stated in the [Exceptions](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/getImageData#Exceptions) section.

See for example https://observablehq.com/@severo/manipulating-video-using-canvas-mdn-tutorial, where the code is on observablehq.com, whereas the video comes from raw.githubusercontent.com. I had to add the `crossorigin="anonymous"` attribute to the `<video>` element. Same exception on https://observablehq.com/@severo/mdn-video-and-canvas-tutorial if you remove `crossorigin="anonymous"`.

**Comment by wbamberg** [comment]
Thanks for the clarification!

This example exists really for the sake of the MDN page at https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API/Manipulating_video_using_canvas, and it works fine there.

As I understand https://developer.mozilla.org/en-US/docs/Web/HTML/CORS_enabled_image, making the example work cross-origin is not as simple as just adding `anonymous`, you also have to configure the server appropriately, so it's not a complete solution in itself.

In fact, the reason we added the example to GitHub was exactly to fix this issue (https://github.com/mdn/dom-examples/pull/29, https://bugzilla.mozilla.org/show_bug.cgi?id=1501297) without having to change the server.

So I think this PR is out of scope for us.

**Comment by severo** [comment]
OK, I understand, you're right. Thanks for taking time to review and comment.

**Pull request closed without merging**
