### PR TITLE
Fix a Nu HTML checker warning

### PR DESCRIPTION
**Pull request by MrBrain295**

### CODE REVIEW

**Comment by teoli2003** [comment]
Can you elaborate on what this PR changes? This is not an HTML change and I don't see what it does to HTML validation warning.

**Comment by MrBrain295** [comment]
The font size was set to be reliant on the viewport but this changes the way the font size is defined.

**Comment by teoli2003** [comment]
Yes, I see this. I still don't understand why this has an impact on HTML validation.

**Comment by MrBrain295** [comment]
Sorry, last time I ran it I remember seeing an error but they doesn’t seem to be the case.

**Pull request closed without merging**
