### PR TITLE
Improving popover API UI help example

### PR DESCRIPTION
**Pull request by chrisdavidmills**
In his review of my [popover API docs updates](https://github.com/mdn/content/pull/26413/), @wbamberg [asked for an update to my UI help example](https://github.com/mdn/content/pull/26413/#discussion_r1179793066). This PR provides that update.

### CODE REVIEW

**Comment by wbamberg** [comment]
Thanks! Is there a branch where this is getting rendered, so I can see it?

(What I do in cases like this: set my gh-pages branch to the branch for the PR (https://github.com/chrisdavidmills/dom-examples/tree/popover-api-improvements here I think))

**Comment by chrisdavidmills** [comment]
> Thanks! Is there a branch where this is getting rendered, so I can see it?

Ummm, no, sorry. I didn't even think to do that.

> (What I do in cases like this: set my gh-pages branch to the branch for the PR (https://github.com/chrisdavidmills/dom-examples/tree/popover-api-improvements here I think))

Oh, so you mean, when I create the PR, set the PR to compare as gh-pages instead of main? I'm not sure I understand how this would all work; I'll have to do some research.

**Review by wbamberg — APPROVED** [review]
👍 thank you!

**Comment by wbamberg** [comment]
> Figured it out; here you go: https://chrisdavidmills.github.io/dom-examples/popover-api/toggle-help-ui/

Yes, that's exactly what I meant. Thank you!

**Pull request merged**
